os: Visual Studio 2015
configuration: Release
platform: Any CPU

before_build:
  - nuget-restore

build:
  verbosity: minimal

test:
  assemblies:
    - **\output\$(configuration)\MicroFlow.Test.dll
    - **\output\portable\$(configuration)\MicroFlow.Test.dll